/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'lucasj8' at '5/28/16 7:52 PM' with Gradle 2.13
 *
 * @author lucasj8, @date 5/28/16 7:52 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
